name: Node JS

on:
    push:
        paths:
            - "information/**.json"
            - "localizations/**.json"

jobs:
    run_scripts:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run Node.js Scripts
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
            - run: find ./scripts -type f -regex '.*m?js' -exec node {} \;
            - name: Commit and push changes
              run: |
                  git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git config --global user.name "github-actions[bot]"
                  git add -A
                  if ! git diff-index --quiet HEAD; then git commit -m "chore(resources): Organize files" && git push; fi
